# Generated by Django 5.2.15 on 2026-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Lector'), ('reviewer', 'Redactor'), ('editor', 'Editor')], default='reader', max_length=10),
        ),
    ]
